tests: add dbt-fal to fal-cli integration tests (#679)
* fix: FalDbt init with dbt-fal

Initializing FalDbt in a directory other than project_dir was causing this
error:

```
dbt.exceptions.DbtProjectError: Runtime Error
  no dbt_project.yml found at expected path [redacted]/dbt_project.yml
```

* fix: fal write_relation with dbt-fal

* tests: add dbt-fal + postgres to integration tests

* fix: cli unit tests in gh-actions

* test: install local dbt-fal in integration tests

* PR comments