fix: FalDbt init with dbt-fal
Initializing FalDbt in a directory other than project_dir was causing this
error:

```
dbt.exceptions.DbtProjectError: Runtime Error
  no dbt_project.yml found at expected path [redacted]/dbt_project.yml
```